{
	"Animations":[
		{
			"Name":"Attack_Slash1_Root",
			"Scripts":[
				{
					"Time": 15,
					"Type": "Attack",

					"PowerRate": 1.0,
					"Duration": 5,
					"HitStop": 10,
					"HitInterval": 10
				},
				{
					"Time": 20,
					"Type": "PopPrefab",
					"PrefabFilename": "Data\\Effect\\HitEffect.pref"
				},
				{
					"Time": 30,
					"Type": "AttackCancel",

					"NextAnimeName": "Attack_Slash2_Root"
				}
			]
		}
	]
}